apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-bus-websocket-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grpc-bus-websocket-proxy
    spec:
      containers:
      - name: grpc-bus-websocket-proxy
        image: gabrielgrant/grpc-bus-websocket-proxy:0.1.1-debug3
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-bus-websocket-proxy-svc
spec:
  ports:
  - name: grpc-port
    port: 8081
    nodePort: 32082
  selector:
    run: grpc-bus-websocket-proxy
  type: NodePort
